### ISSUE TITLE
Trouble accessing columns with dot in name

### ISSUE THREAD

**Issue by Legless** [dchaplinsky/thebeast#10]
While reading CSV (haven't tested other readers), there's no easy way to access columns with dot in name.

E.g. , having a column named `vkontakte.nickName`, only way I could access it's value is by using template.

This is **not** working:
```yaml
alias:
  column: vkontakte.nickName
```

This is working:
```yaml
alias:
  template: '{{record["vkontakte.nickName"]}}'
```

Probably this because `_resolve_column` calls `jmespath_results_as_array` without escaping column name, but I'm too dumb to find&fix this.

**Comment by dchaplinsky** [comment]
Well, you can use jmespath like `locations[]."name.city"` on the data like that:
```json
{
  "locations": [
    {"name.city": "Seattle", "state": "WA"},
    {"name.city": "New York", "state": "NY"},
    {"name.city": "Bellevue", "state": "WA"},
    {"name.city": "Olympia", "state": "WA"}
  ]
}
```

(you could try it [here](https://jmespath.org))

And you can use it in yaml like this:
```yaml
alias:
  column: '"vkontakte.nickName"'
```

**Comment by Legless** [comment]
It works this way, thank you. ♥
